/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
@Test
    public void TestArrayShift() {
        int[] pseudoArray = new int[]{1,2,3,5,6,7};
        int[] shiftedArray = new int[]{1,2,3,4,5,6,7};
        assertArrayEquals(
                "The Array returns with the new value",
                shiftedArray,
                ArrayShift.shiftArray(pseudoArray, 4)

        );
}
@Test
    public void TestBinarySearch() {
        int[] testArr = new int[]{1,2,3,5,6,7};
        int testSearchNumber = 3;
        assertEquals (
                "The method should search the array for the search value and return the value, if the value " +
                        "is not in the array the method should return -1",
                3,
                BinarySearch.binarySearch(testArr, 5));


    }
}
